/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unodistribuido;

import Barajeador.Carta;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author roafi
 */
public class AccionCarta extends javax.swing.JDialog {

    private Carta carta;
    private Point initialClick;
    private Cliente cliente;
    private int ncartas;
    private List<Carta> cards;

    public AccionCarta(Carta carta,Cliente cliente) {
        super(cliente);
        initComponents();
        this.cliente=cliente;
        this.carta=carta;
        setSize(320,180);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(cliente);
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                initialClick = e.getPoint();
                getComponentAt(initialClick);
            }
        });
        
        addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {

            // get location of Window
            int thisX = getMe().getLocation().x;
            int thisY = getMe().getLocation().y;

            // Determine how much the mouse moved since the initial click
            int xMoved = e.getX() - initialClick.x;
            int yMoved = e.getY() - initialClick.y;

            // Move window to this position
            int X = thisX + xMoved;
            int Y = thisY + yMoved;
            getMe().setLocation(X, Y);
        }
    });
        Image img=new ImageIcon(getClass().getResource("imagenes/baraja/"+carta.getCarta()+".png")).getImage();
        ImageIcon img2=new ImageIcon(img.getScaledInstance(90, 135, Image.SCALE_FAST)); 
        lblCarta.setIcon(img2);
        btnRobar.setVisible(false);
        btnReto.setVisible(false);
        setVisible(true);
        requestFocus();
        
    }
    
    public AccionCarta(Cliente cliente,int ncartas,List cards) {
        super(cliente);
        initComponents();
        this.cards=cards;
        this.cliente=cliente;
        this.carta=carta;
        this.ncartas=ncartas;
        setSize(320,180);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(cliente);
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                initialClick = e.getPoint();
                getComponentAt(initialClick);
            }
        });
        
        addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {

            // get location of Window
            int thisX = getMe().getLocation().x;
            int thisY = getMe().getLocation().y;

            // Determine how much the mouse moved since the initial click
            int xMoved = e.getX() - initialClick.x;
            int yMoved = e.getY() - initialClick.y;

            // Move window to this position
            int X = thisX + xMoved;
            int Y = thisY + yMoved;
            getMe().setLocation(X, Y);
        }
    });
        Image img=new ImageIcon(getClass().getResource("imagenes/baraja/E01.png")).getImage();
        ImageIcon img2=new ImageIcon(img.getScaledInstance(90, 135, Image.SCALE_FAST)); 
        lblCarta.setIcon(img2);
        btnJugar.setVisible(false);
        btnConservar.setVisible(false);
        setVisible(true);
        requestFocus();
        
    }
    
    private AccionCarta getMe()
    {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarta = new javax.swing.JLabel();
        btnConservar = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnRobar = new javax.swing.JButton();
        btnReto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(320, 180));
        getContentPane().setLayout(null);

        lblCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/baraja/fondo2.png"))); // NOI18N
        lblCarta.setText("jLabel2");
        lblCarta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblCarta);
        lblCarta.setBounds(100, 30, 90, 135);

        btnConservar.setBackground(new java.awt.Color(230, 7, 12));
        btnConservar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnConservar.setForeground(new java.awt.Color(255, 255, 255));
        btnConservar.setText("Conservar");
        btnConservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConservarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConservar);
        btnConservar.setBounds(210, 110, 90, 30);

        btnJugar.setBackground(new java.awt.Color(230, 7, 12));
        btnJugar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(210, 60, 90, 30);

        btnRobar.setBackground(new java.awt.Color(255, 102, 0));
        btnRobar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnRobar.setForeground(new java.awt.Color(255, 255, 255));
        btnRobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/otros/jugar.png"))); // NOI18N
        btnRobar.setToolTipText("Jugar!");
        btnRobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRobarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRobar);
        btnRobar.setBounds(225, 100, 60, 60);

        btnReto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/otros/box.png"))); // NOI18N
        btnReto.setToolTipText("Retar!");
        btnReto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetoActionPerformed(evt);
            }
        });
        getContentPane().add(btnReto);
        btnReto.setBounds(225, 30, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/fondos/fondochico.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 320, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConservarActionPerformed
        cliente.ponCartaMano(carta);
        cliente.setNoCerrar(false);
        dispose();
    }//GEN-LAST:event_btnConservarActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        cliente.ponCartaPila(carta);
        cliente.setNoCerrar(false);
        dispose();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnRobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobarActionPerformed
        cliente.come4(ncartas);
        dispose();
    }//GEN-LAST:event_btnRobarActionPerformed

    private void btnRetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetoActionPerformed
        cliente.reto(ncartas, cards,this);
    }//GEN-LAST:event_btnRetoActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConservar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnReto;
    private javax.swing.JButton btnRobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarta;
    // End of variables declaration//GEN-END:variables
}
