/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unodistribuido;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.AffineTransform;
import javax.swing.Timer;

/**
 *
 * @author roafi
 */
public class Reto extends javax.swing.JPanel {
    private final Timer tmrAgitar;
    private int cont,accion;
    private Cliente cliente;
    private int ncartas;
    private boolean banTipo;
    /**
     * Creates new form Reto
     */
    public Reto(Cliente cliente) {
        initComponents();
        this.banTipo=false;
        this.cliente=cliente;
        this.accion=0;
        lblFondo.setVisible(true);
        lblPerdiste.setVisible(false);
        lblGanaste.setVisible(false);
        tmrAgitar=new Timer(60,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Graphics g=lblGuantes.getGraphics();
                double r;
                if (cont>10)
                {
                    if (getAccion()==1)
                    {
                        AudioFilePlayer player;
                        player = new AudioFilePlayer(getClass().getResource("sonidos/retoGanado.wav"),null,0);
                        lblFondo.setVisible(false);
                        lblGuantes.setVisible(false);
                        lblGanaste.setVisible(true);
                        cont=1;
                        setAccion(0);
                        tmrAgitar.setDelay(100);
                    }
                    else if (getAccion()==2)
                    {
                        AudioFilePlayer player;
                        player = new AudioFilePlayer(getClass().getResource("sonidos/retoPerdido.wav"),null,0);
                        lblFondo.setVisible(false);
                        lblGuantes.setVisible(false);
                        lblPerdiste.setVisible(true);
                        cont=1;
                        setAccion(0);
                        tmrAgitar.setDelay(100);
                    }
                    else if(getAccion()==0)
                    {
                        getMe().setVisible(false);
                        if(lblGanaste.isVisible())
                        {
                            if (!banTipo)
                            {
                                cliente.setTurno(true);
                                cliente.setIniciado(true);
                                cliente.retar(ncartas);
                            }
                        }
                        else if (lblPerdiste.isVisible())
                        {
                            if (!banTipo)
                                cliente.retar(0);
                            cliente.come4(ncartas);

                        }
                        else
                        {
                            cliente.come2RU();
                        }
                        cont=1;
                        tmrAgitar.stop();
                    }
                    r = Math.toRadians(0); //se convierte a radianes lo grados
                    
                }
                else if (getAccion()!=0)
                {
                    switch(cont)
                    {
                        case 1:  r = Math.toRadians(45); break;
                        case 2:  r = Math.toRadians(27); break;
                        case 3:  r = Math.toRadians(0); break;
                        case 4:  r = Math.toRadians(-27); break;
                        case 5:  r = Math.toRadians(-45); break;
                        default: r=0; break;
                    }
                    lblFondo.setVisible(true);
                    lblGuantes.setVisible(false);
                    AffineTransform at = new AffineTransform();
                    at.rotate(r, lblGuantes.getSize().width/2,lblGuantes.getSize().height/2); //se asigna el angulo y centro de rotacion
                    ((Graphics2D) g).setTransform(at);
                    getMe().paintImmediately(lblGuantes.getLocation().x, lblGuantes.getLocation().y, lblGuantes.getLocation().x+lblGuantes.getSize().width,lblGuantes.getLocation().y+lblGuantes.getSize().height+75);   
                    lblGuantes.paint(g);
                }
                cont++;
            }          
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFondo = new javax.swing.JLabel();
        lblGuantes = new javax.swing.JLabel();
        lblPerdiste = new javax.swing.JLabel();
        lblGanaste = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/reto/fondo.png"))); // NOI18N
        add(lblFondo);
        lblFondo.setBounds(0, 0, 325, 238);

        lblGuantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/reto/guantes.png"))); // NOI18N
        add(lblGuantes);
        lblGuantes.setBounds(0, 0, 325, 238);

        lblPerdiste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/otros/perdiste.png"))); // NOI18N
        add(lblPerdiste);
        lblPerdiste.setBounds(0, 0, 325, 238);

        lblGanaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unodistribuido/imagenes/otros/ganaste.png"))); // NOI18N
        add(lblGanaste);
        lblGanaste.setBounds(0, 0, 325, 238);
    }// </editor-fold>//GEN-END:initComponents
    public void setAccion(int accion)
    {
        this.accion=accion;
    }
    public int getAccion()
    {
        return accion;
    }
    public void iniciar(int accion,int ncartas,boolean ban)
    {
        this.banTipo=ban;
        this.setVisible(true);
        this.ncartas=ncartas;
        this.accion=accion;
        lblFondo.setVisible(true);
        lblGuantes.setVisible(true);
        lblPerdiste.setVisible(false);
        lblGanaste.setVisible(false);
        AudioFilePlayer player;
        player = new AudioFilePlayer(getClass().getResource("sonidos/reto.wav"),null,0);
        tmrAgitar.start();
       
    }
    
    public Reto getMe()
    {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGanaste;
    private javax.swing.JLabel lblGuantes;
    private javax.swing.JLabel lblPerdiste;
    // End of variables declaration//GEN-END:variables
}
